apiVersion: v1
kind: Secret
metadata:
  name: {{ include "OpenMetadata.fullname" . }}-secret
type: Opaque
data:
{{- if not .Values.global.fernetkey.secretKey }}
  FERNET_KEY: {{ .Values.global.fernetkey.value | b64enc | quote }}
{{ end }}